name: noheva_visitor_ui
description: Noheva visitor UI project

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.9.0

environment:
  sdk: ">=3.0.6 <4.0.0"

scripts:
  generate:
    client: >
      flutter pub run build_runner build --delete-conflicting-outputs &&
      flutter pub get noheva-api

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  openapi_generator_annotations: ^4.0.0
  flutter_dotenv: ^5.1.0
  simple_logger: ^1.9.0+2
  noheva_api:
    path: noheva-api
  device_info_plus: ^9.0.3
  mqtt_client: ^10.0.0
  typed_data: ^1.3.1
  json_annotation: any
  android_id: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  openapi_generator: ^4.0.0
  build_runner: ^2.1.8
  json_serializable: any

flutter:
  uses-material-design: true
  assets:
    - .env
